---
- name: Generate VSCode settings files
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - dsakurai.common

  tasks:
    - name: Run VSCode role
      ansible.builtin.include_role:
        name: "dsakurai.common.{{ role }}"
